# Try to find ev++.h for Libev


IF (LIBEV_INCLUDE_DIRS)
	# Already in cache, be silent
	SET(LIBEV_FIND_QUIETLY TRUE)
ENDIF (LIBEV_INCLUDE_DIRS)

FIND_LIBRARY(LIBEV_LIBRARIES NAMES ev)
FIND_PATH(LIBEV_INCLUDE_DIRS ev++.h
	PATH_SUFFIXES include/ev include
	)

IF(LIBEV_INCLUDE_DIRS)
	SET(LIBEV_FOUND TRUE)
ENDIF(LIBEV_INCLUDE_DIRS)

IF(LIBEV_FOUND)
	set(CMAKE_REQUIRED_INCLUDES ${LIBEV_INCLUDE_DIRS})
	set(CMAKE_REQUIRED_INCLUDES)
	IF(NOT LIBEV_FIND_QUIETLY)
		MESSAGE(STATUS "Found Libev headers: ${LIBEV_INCLUDE_DIRS}/ev++.h")
		MESSAGE(STATUS "Found Libev lib: ${LIBEV_LIBRARIES}")
	ENDIF(NOT LIBEV_FIND_QUIETLY)
ELSE(LIBEV_FOUND)
	IF(LIBEV_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find Libev")
	ENDIF(LIBEV_FIND_REQUIRED)
ENDIF(LIBEV_FOUND)

MARK_AS_ADVANCED(
	LIBEV_INCLUDE_DIRS
	LIBEV_LIBRARIES
	LIBEV_SECOND_ARGUMENT_IS_CONST
	)
