# 
#
# Tries to find libxcb and libxcb-screensaver and sets following variables according to found capabilities:
#
# XCB_FOUND
# XCB_INCLUDE_DIRS
# XCB_LIBRARIES

FIND_PACKAGE(PkgConfig)
PKG_CHECK_MODULES(PKG_XCB xcb xcb-screensaver)

FIND_PATH(XCB_XCB_INCLUDE_DIRS xcb/xcb.h
	HINTS
	${PKG_XCB_INCLUDE_DIRS}
	${PKG_XCB_INCLUDEDIR}
	PATH_SUFFIXES xcb
)

FIND_PATH(XCB_SCREENSAVER_INCLUDE_DIRS xcb/screensaver.h
	HINTS
	${PKG_XCB_INCLUDE_DIRS}
	${PKG_XCB_INCLUDEDIR}
	PATH_SUFFIXES xcb
)

FIND_LIBRARY(XCB_XCB_LIBRARIES xcb
	HINTS ${PKG_XCB_LIBRARY_DIRS}
)

FIND_LIBRARY(XCB_SCREENSAVER_LIBRARIES xcb-screensaver
	HINTS ${PKG_XCB_LIBRARY_DIRS}
)

IF(XCB_XCB_LIBRARIES AND XCB_XCB_INCLUDE_DIRS AND XCB_SCREENSAVER_LIBRARIES AND XCB_SCREENSAVER_INCLUDE_DIRS)
	SET(XCB_FOUND true)
ENDIF()

IF(XCB_FIND_REQUIRED AND NOT XCB_FOUND)
	MESSAGE(FATAL_ERROR "Could not find libxcb or libxcb-screensaver")
ENDIF()

SET(XCB_INCLUDE_DIRS ${XCB_XCB_INCLUDE_DIRS} ${XCB_SCREENSAVER_INCLUDE_DIRS})
SET(XCB_LIBRARIES ${XCB_XCB_LIBRARIES} ${XCB_SCREENSAVER_LIBRARIES})

MARK_AS_ADVANCED(
	XCB_INCLUDE_DIRS
	XCB_LIBRARIES
	XCB_FOUND
)
